apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-cert
  namespace: {{index . "namespace"}}
spec:
  dnsNames:
    - home-assistant.{{ index . "domain"}}
  secretName: home-assistant-cert
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
