apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: {{ index . "namespace" }}
spec:
  serviceAccountName: {{ index . "serviceAccountName" }}
  releaseName: home-assistant
  chart:
    spec:
      chart: app-template
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
  interval: 30m
  install:
    remediation:
      retries: 3
  test:
    enable: false
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      pullPolicy: IfNotPresent
      tag: "2022.11"
    strategy:
      type: Recreate
    service:
      main:
        ports:
          http:
            port: 8123
    ingress:
      main:
        {{- if and (index . "isNginxInstalled") (index . "isDomainInstalled") }}
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.org/websocket-services: home-assistant
        hosts:
          - host: home-assistant.{{ index . "domain"}}
            paths:
              - path: /
                pathType: Prefix
        {{- else }}
        enable: false
        {{- end }}
        {{- if and (index . "isNginxInstalled") (index . "isDomainInstalled") (index . "isCertManagerInstalled") }}
        tls:
          - secretName: home-assistant-cert
            hosts:
              - home-assistant.{{ index . "domain"}}
        {{- end }}
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 2Gi
        mountPath: /config